### PR TITLE
Properly handle #goto_go not defined

### PR DESCRIPTION
**Pull request by stblassitude**
On for example the login page, there is no DOM element #goto_go. Avoid a 
JS error in this case.

### CODE REVIEW

**Comment by stblassitude** [comment]
Apologies for the whitespace changes, I didn't realize my editor did that. I can redo it if it bothers you.

**Review by turnermm — COMMENTED** [review]
Could you clean this up, so that your changes are more evident?  Thnx.

**Comment by stblassitude** [comment]
I hope this works better for you?

**Review by turnermm — APPROVED** [review]

**Comment by turnermm** [comment]
Thanks.  Makes sense.

**Pull request merged**
